/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function classifyCsv(input: string, cls: Buffer, inputBuf: Buffer): number

export declare function classifyCsvBuf(input: Buffer, cls: Buffer): number

export declare function inferCsv(input: Buffer, out: Buffer, hasHeaders: boolean, maxSamples: number): number

export declare function inferCsvJs(input: string, inputBuf: Buffer, out: Buffer, hasHeaders: boolean, maxSamples: number): number

export declare function memchrIndex(input: Buffer, needle: number): number

export declare function napiAcceptBigint(n: bigint): number

export declare function napiAcceptBool(b: boolean): number

export declare function napiAcceptBuffer(buf: Buffer): number

export declare function napiAcceptBufferMut(buf: Buffer): number

export declare function napiAcceptF64(n: number): number

export declare function napiAcceptString(s: string): number

export declare function napiAcceptTwoBuffers(a: Buffer, b: Buffer): number

export declare function napiAcceptU32(n: number): number

export declare function napiNoop(): number

export declare function napiSumBytes(buf: Buffer): number

export declare function parseCsv(input: Buffer, cmdBuf: Buffer, offset: number, typed: boolean, strRow: boolean): number

export declare function parseCsvJs(input: string, inputBuf: Buffer, cmdBuf: Buffer, offset: number, typed: boolean, strRow: boolean): number

export declare function parseWithTypes(input: Buffer, posBuf: Buffer, output: Buffer, colTypes: Buffer): number

export declare function parseWithTypesJs(input: string, inputBuf: Buffer, posBuf: Buffer, output: Buffer, colTypes: Buffer): number

export declare function parseWithTypesJsUtf16(input: string, inputBuf: Buffer, posBuf: Buffer, output: Buffer, colTypes: Buffer): number

export declare function scanFieldsBuf(input: Buffer, out: Buffer): number

export declare function scanFieldsCompact(input: Buffer, out: Buffer): number

export declare function scanFieldsCompactJs(input: string, inputBuf: Buffer, out: Buffer, content: Buffer): number

export declare function scanFieldsJs(input: string, inputBuf: Buffer, out: Buffer): number

export declare function scanParseWithTypesJs(input: string, inputBuf: Buffer, posBuf: Buffer, output: Buffer, colTypes: Buffer): number

export declare function scanParseWithTypesJsUtf16(input: string, inputBuf: Buffer, posBuf: Buffer, output: Buffer, colTypes: Buffer): number

export declare function scanPositionsJs(input: string, inputBuf: Buffer, out: Buffer): number
