/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function fusedTypedParseJs(input: string, inputBuf: Buffer, posBuf: Buffer, output: Buffer, sideBuf: Buffer, descriptor: Buffer, hasHeaders: boolean, maxSamples: number): number

export declare function inferCsv(input: Buffer, out: Buffer, hasHeaders: boolean, maxSamples: number): number

export declare function inferCsvJs(input: string, inputBuf: Buffer, out: Buffer, hasHeaders: boolean, maxSamples: number): number

export declare function scanFieldsCompact(input: Buffer, out: Buffer): number

export declare function scanFieldsCompactJs(input: string, inputBuf: Buffer, out: Buffer, content: Buffer): number
